/*
 *
 * This file is generated by gen_constants.pl
 * Do not edit by hand!
 *
 */

SV *enum2sv_ConnStatusType[8];
SV *enum2sv_CopyResultFlag[9];
SV *enum2sv_ExecStatusType[6];
SV *enum2sv_PGTransactionStatusType[6];
SV *enum2sv_PostgresPollingStatusType[3];

static void
init_constants(void) {
    enum2sv_ConnStatusType[0] = make_constant("CONNECTION_OK", 13, CONNECTION_OK);
    enum2sv_ConnStatusType[1] = make_constant("CONNECTION_BAD", 14, CONNECTION_BAD);
    enum2sv_ConnStatusType[2] = make_constant("CONNECTION_STARTED", 18, CONNECTION_STARTED);
    enum2sv_ConnStatusType[3] = make_constant("CONNECTION_MADE", 15, CONNECTION_MADE);
    enum2sv_ConnStatusType[4] = make_constant("CONNECTION_AWAITING_RESPONSE", 28, CONNECTION_AWAITING_RESPONSE);
    enum2sv_ConnStatusType[5] = make_constant("CONNECTION_AUTH_OK", 18, CONNECTION_AUTH_OK);
    enum2sv_ConnStatusType[6] = make_constant("CONNECTION_SETENV", 17, CONNECTION_SETENV);
    enum2sv_ConnStatusType[7] = make_constant("CONNECTION_SSL_STARTUP", 22, CONNECTION_SSL_STARTUP);

    enum2sv_CopyResultFlag[0] = make_constant("COPYRESULTFLAG_0", 16, 0);
    enum2sv_CopyResultFlag[1] = make_constant("PG_COPYRES_ATTRS", 16, PG_COPYRES_ATTRS);
    enum2sv_CopyResultFlag[2] = make_constant("PG_COPYRES_TUPLES", 17, PG_COPYRES_TUPLES);
    enum2sv_CopyResultFlag[3] = make_constant("COPYRESULTFLAG_3", 16, 3);
    enum2sv_CopyResultFlag[4] = make_constant("PG_COPYRES_EVENTS", 17, PG_COPYRES_EVENTS);
    enum2sv_CopyResultFlag[5] = make_constant("COPYRESULTFLAG_5", 16, 5);
    enum2sv_CopyResultFlag[6] = make_constant("COPYRESULTFLAG_6", 16, 6);
    enum2sv_CopyResultFlag[7] = make_constant("COPYRESULTFLAG_7", 16, 7);
    enum2sv_CopyResultFlag[8] = make_constant("PG_COPYRES_NOTICEHOOKS", 22, PG_COPYRES_NOTICEHOOKS);

    enum2sv_ExecStatusType[0] = make_constant("PGRES_COMMAND_OK", 16, PGRES_COMMAND_OK);
    enum2sv_ExecStatusType[1] = make_constant("PGRES_TUPLES_OK", 15, PGRES_TUPLES_OK);
    enum2sv_ExecStatusType[2] = make_constant("PGRES_COPY_OUT", 14, PGRES_COPY_OUT);
    enum2sv_ExecStatusType[3] = make_constant("PGRES_COPY_IN", 13, PGRES_COPY_IN);
    enum2sv_ExecStatusType[4] = make_constant("PGRES_BAD_RESPONSE", 18, PGRES_BAD_RESPONSE);
    enum2sv_ExecStatusType[5] = make_constant("PGRES_NONFATAL_ERROR", 20, PGRES_NONFATAL_ERROR);

    enum2sv_PGTransactionStatusType[0] = make_constant("PQTRANS_IDLE", 12, PQTRANS_IDLE);
    enum2sv_PGTransactionStatusType[1] = make_constant("PQTRANS_ACTIVE", 14, PQTRANS_ACTIVE);
    enum2sv_PGTransactionStatusType[2] = make_constant("PQTRANS_INTRANS", 15, PQTRANS_INTRANS);
    enum2sv_PGTransactionStatusType[3] = make_constant("PQTRANS_INERROR", 15, PQTRANS_INERROR);
    enum2sv_PGTransactionStatusType[4] = make_constant("PQERRORS_TERSE", 14, PQERRORS_TERSE);
    enum2sv_PGTransactionStatusType[5] = make_constant("PQERRORS_DEFAULT", 16, PQERRORS_DEFAULT);

    enum2sv_PostgresPollingStatusType[0] = make_constant("PGRES_POLLING_READING", 21, PGRES_POLLING_READING);
    enum2sv_PostgresPollingStatusType[1] = make_constant("PGRES_POLLING_WRITING", 21, PGRES_POLLING_WRITING);
    enum2sv_PostgresPollingStatusType[2] = make_constant("PGRES_POLLING_OK", 16, PGRES_POLLING_OK);

}
static SV *
ConnStatusType2sv(I32 ix) {
    SV *sv;
    ix -= CONNECTION_OK;
    if ((ix < 0) || (ix >= 8)) {
        return newSViv(ix);
    }
    sv = newSVsv(enum2sv_ConnStatusType[ix]);
    return sv;
}

static SV *
CopyResultFlag2sv(I32 ix) {
    SV *sv;
    ix -= 1 - PG_COPYRES_ATTRS;
    if ((ix < 0) || (ix >= 9)) {
        return newSViv(ix);
    }
    sv = newSVsv(enum2sv_CopyResultFlag[ix]);
    return sv;
}

static SV *
ExecStatusType2sv(I32 ix) {
    SV *sv;
    ix -= PGRES_COMMAND_OK;
    if ((ix < 0) || (ix >= 6)) {
        return newSViv(ix);
    }
    sv = newSVsv(enum2sv_ExecStatusType[ix]);
    return sv;
}

static SV *
PGTransactionStatusType2sv(I32 ix) {
    SV *sv;
    ix -= PQTRANS_IDLE;
    if ((ix < 0) || (ix >= 6)) {
        return newSViv(ix);
    }
    sv = newSVsv(enum2sv_PGTransactionStatusType[ix]);
    return sv;
}

static SV *
PostgresPollingStatusType2sv(I32 ix) {
    SV *sv;
    ix -= PGRES_POLLING_READING;
    if ((ix < 0) || (ix >= 3)) {
        return newSViv(ix);
    }
    sv = newSVsv(enum2sv_PostgresPollingStatusType[ix]);
    return sv;
}

